# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-18 16:44+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: api/serializers/entry.py:125
msgid "will not be published"
msgstr "Werden nicht veröffentlicht"

#: api/serializers/relation.py:23
msgid "Relation already exists"
msgstr "Verknüpfung existiert bereits"

#: api/serializers/relation.py:30 api/views.py:187
msgid "Current user is not the owner of this entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

#: api/views.py:191 api/views.py:776 api/views.py:801
#: media_server/serializers.py:30
msgid "Entry does not exist"
msgstr "Eintrag existiert nicht"

#: api/views.py:272
msgid "Schema not found for the given query"
msgstr "Kein Schema gefunden"

#: api/views.py:311 api/views.py:771
msgid "User does not exist"
msgstr "Benutzer existiert nicht"

#: core/models.py:119
#, python-format
msgid "Type %(type_source)s does not belong to any active schema"
msgstr "Typ %(type_source)s gehört zu keinem aktiven Schema"

#: core/models.py:126
#, python-format
msgid "Invalid data: %(error)s"
msgstr "Ungültige Daten: %(error)s"

#: core/models.py:129
msgid "Data without type"
msgstr "Daten ohne Typ"

#: core/models.py:165
msgid "Both entries must belong to the same user"
msgstr "Beide Einträge müssen demselben Benutzer gehören"

#: core/schemas/__init__.py:26
msgid "Schemas improperly configured"
msgstr "Schemata ungenügend konfiguriert"

#: core/schemas/__init__.py:64
msgid "Active schemas contain duplicate types"
msgstr "Aktive Schemata enthalten Duplikate"

#: core/schemas/entries/exhibition.py:45 core/schemas/general.py:100
#: core/schemas/general.py:116 core/schemas/general.py:150
#: core/schemas/general.py:173 core/schemas/general.py:189
#: core/schemas/general.py:210 core/schemas/general.py:232
msgid "and"
msgstr "und"

#: core/utils.py:6
#, python-format
msgid "Enter %(label)s"
msgstr "%(label)s eintragen"

#: core/validators.py:15
#, python-format
msgid "Invalid type: %(error)s"
msgstr "Ungültiger Typ: %(error)s"

#: core/validators.py:23
msgid "Keywords contains duplicate entries"
msgstr "Schlagwörter enthalten Duplikate"

#: core/validators.py:25
#, python-format
msgid "Invalid keywords: %(error)s"
msgstr "Ungültige Schlagwörter: %(error)s"

#: core/validators.py:39
msgid "Same language is defined multiple times"
msgstr "Dieselbe Sprache wird mehrmals definiert"

#: core/validators.py:41
#, python-format
msgid "Invalid texts: %(error)s"
msgstr "Ungültige Texte: %(error)s"

#: media_server/serializers.py:33
msgid "Current user is not the owner of entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

#: media_server/validators.py:17
#, python-format
msgid "Invalid license: %(error)s"
msgstr "Ungültige Lizenz: %(error)s"

#: media_server/validators.py:22
msgid "Invalid license"
msgstr "Ungültige Lizenz"

#: media_server/views.py:98 media_server/views.py:179 media_server/views.py:224
msgid "Current user is not the owner of this media object"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Medienobjekts"

#: media_server/views.py:111 media_server/views.py:187
#: media_server/views.py:232
msgid "Media object does not exist"
msgstr "Medienobjekt existiert nicht"

#: media_server/views.py:129
msgid "No space left for user"
msgstr "Kein Speicherplatz mehr für diesen Benutzer"

#: portfolio/settings.py:247
msgid "German"
msgstr "Deutsch"

#: portfolio/settings.py:248
msgid "English"
msgstr "Englisch"
