# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-03-13 15:48+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: api/serializers/relation.py:20
msgid "Relation already exists"
msgstr "Verknüpfung existiert bereits"

#: api/serializers/relation.py:27 api/views.py:115
msgid "Current user is not the owner of this entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

#: api/views.py:119 media_server/serializers.py:15
msgid "Entry does not exist"
msgstr "Eintrag existiert nicht"

#: api/views.py:180
msgid "Schema not found for the given query."
msgstr "Kein Schemata gefunden"

#: core/models.py:55
msgid "Invalid data: {}"
msgstr "Ungültige Daten: {}"

#: core/models.py:57
msgid "Data without type"
msgstr "Daten ohne Typ"

#: core/models.py:90
msgid "Both entries must belong to the same user"
msgstr "Beide Einträge müssen demselben Benutzer gehören"

#: core/schemas/__init__.py:13
msgid "Schemas improperly configured"
msgstr "Schemata ungenügend konfiguriert"

#: core/schemas/__init__.py:31
msgid "Active schemas contain duplicate types"
msgstr "Aktive Schemata enthalten Duplikate"

#: core/validators.py:12
msgid "Keywords contains duplicate entries"
msgstr "Schlagwörter enthalten Duplikate"

#: core/validators.py:14
msgid "Invalid keywords: {}"
msgstr "Ungültige Schlagwörter: {}"

#: core/validators.py:27
msgid "Same language is defined multiple times"
msgstr "Dieselbe Sprache wird mehrmals definiert"

#: core/validators.py:29
msgid "Invalid texts: {}"
msgstr "Ungültige Texte: {}"

#: media_server/serializers.py:18
msgid "Current user is not the owner of entry"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Eintrags"

#: media_server/views.py:89 media_server/views.py:151 media_server/views.py:194
msgid "Current user is not the owner of this media object"
msgstr "Der momentane Benutzer ist nicht der Besitzer dieses Medienobjekts"

#: media_server/views.py:103 media_server/views.py:162
#: media_server/views.py:202
msgid "Media object does not exist"
msgstr "Medienobjekt existiert nicht"

#: media_server/views.py:117
msgid "No space left for user"
msgstr "Kein Speicherplatz mehr für diesen Benutzer"

#: portfolio/settings.py:241
msgid "German"
msgstr "Deutsch"

#: portfolio/settings.py:242
msgid "English"
msgstr "Englisch"
